FORMAT: 1A
HOST: http://localhost:8001/

# Tweets

Tweets es una api simple para pedir comentarios de twitter relevantes a una pelicula o serie de television, y los guarda en una base de datos

## Recoleccion de Tweets [/api/v2/tweets?t={nombre_pelicula}]

### Guardar Tweets  [GET]
+ Parameters:
    + nombre_pelicula(string) nombre de la pelicula a buscar
    
+ Response 204 
